Fix broken ABI, fix makefiles

diff --git a/test/perf/Makefile b/test/perf/Makefile
--- a/test/perf/Makefile
+++ b/test/perf/Makefile
@@ -18,20 +18,26 @@ $(BUILD_DIR)/test/perf/%: %.al make_dir
 	echo $(patsubst %.al, %, $<) > $@
 
 	echo "calias x86_64" >> $@
-	$(BUILD_DIR)/calias -a $(ALFLAGS) $< -o $(patsubst %.al, $(BUILD_DIR)/test/perf/x86_64/%.o, $<)
-	ld $(LDFLAGS) -o $(patsubst %.al, $(BUILD_DIR)/test/perf/x86_64/%, $<) $(patsubst %.al, $(BUILD_DIR)/test/perf/x86_64/%.o, $<) $(OBJS_ARCH) $(OBJS_ALTLIB)
-	{ time -p $(patsubst %.al, $(BUILD_DIR)/test/perf/x86_64/%, $<) ; } 2>&1 | grep real | awk '{print $$2}' >> $@
+	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/x86_64/%, $<))
+	$(BUILD_DIR)/calias -a $(ALFLAGS) $< -o $($@_DIR).o
+	ld $(LDFLAGS) -o $($@_DIR) $($@_DIR).o $(OBJS_ARCH) $(OBJS_ALTLIB)
+	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
+	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
 
 	echo "calias C" >> $@
-	$(BUILD_DIR)/calias -a -b c $(ALFLAGS) $< -o $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%.c, $<)
-	gcc -fno-stack-protector -O2 -g -c $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%.c, $<) -o $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%.o, $<) -no-pie
-	ld $(LDFLAGS) -o $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%, $<) $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%.o, $<) $(OBJS_ARCH) $(OBJS_ALTLIB)
-	{ time -p $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%, $<) ; } 2>&1 | grep real | awk '{print $$2}' >> $@
+	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%, $<))
+	$(BUILD_DIR)/calias -a -b c $(ALFLAGS) $< -o $($@_DIR).c
+	gcc -fno-stack-protector -O2 -g -c $($@_DIR).c -o $($@_DIR).o -no-pie
+	ld $(LDFLAGS) -o $($@_DIR) $($@_DIR).o $(OBJS_ARCH) $(OBJS_ALTLIB)
+	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
+	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
 
 	echo "gcc" >> $@
-	gcc $(CFLAGS) -c -O2 $(patsubst %.al, %.c, $<) -o $(patsubst %.al, $(BUILD_DIR)/test/perf/gcc/%.o, $<)
-	gcc $(LDFLAGS) -o $(patsubst %.al, $(BUILD_DIR)/test/perf/gcc/%, $<) $(patsubst %.al, $(BUILD_DIR)/test/perf/gcc/%.o, $<) $(OBJS_ARCH) $(OBJS_STDLIB)
-	{ time -p $(patsubst %.al, $(BUILD_DIR)/test/perf/gcc/%, $<) ; } 2>&1 | grep real | awk '{print $$2}' >> $@
+	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/gcc/%, $<))
+	gcc $(CFLAGS) -c -O2 $(patsubst %.al, %.c, $<) -o $($@_DIR).o
+	gcc $(LDFLAGS) -o $($@_DIR) $($@_DIR).o $(OBJS_ARCH) $(OBJS_STDLIB)
+	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
+	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
 
 make_dir:
 	mkdir -p $(BUILD_DIR)/test/perf/x86_64
