Add dfs perf test

diff --git a/test/perf/Makefile b/test/perf/Makefile
--- a/test/perf/Makefile
+++ b/test/perf/Makefile
@@ -15,8 +15,6 @@ OBJS_STDLIB := $(wildcard $(BUILD_DIR)/stdlib/*.o)
 all: $(REPORTS)
 
 $(BUILD_DIR)/test/perf/%: %.al make_dir
-	echo $(patsubst %.al, %, $<) > $@
-
 	echo "calias x86_64" >> $@
 	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/x86_64/%, $<))
 	$(BUILD_DIR)/calias -a $(ALFLAGS) $< -o $($@_DIR).o
@@ -24,8 +22,8 @@ $(BUILD_DIR)/test/perf/%: %.al make_dir
 	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
 	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
 
-	echo "calias C" >> $@
-	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/c/%, $<))
+	echo "calias C + gcc" >> $@
+	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/c-gcc/%, $<))
 	$(BUILD_DIR)/calias -a -b c $(ALFLAGS) $< -o $($@_DIR).c
 	gcc -fno-stack-protector -O2 -g -c $($@_DIR).c -o $($@_DIR).o -no-pie
 	ld $(LDFLAGS) -o $($@_DIR) $($@_DIR).o $(OBJS_ARCH) $(OBJS_ALTLIB)
@@ -39,7 +37,24 @@ $(BUILD_DIR)/test/perf/%: %.al make_dir
 	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
 	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
 
+	echo "calias C + clang" >> $@
+	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/c-clang/%, $<))
+	$(BUILD_DIR)/calias -a -b c $(ALFLAGS) $< -o $($@_DIR).c
+	clang -fno-stack-protector -O2 -g -c $($@_DIR).c -o $($@_DIR).o
+	ld $(LDFLAGS) -o $($@_DIR) $($@_DIR).o $(OBJS_ARCH) $(OBJS_ALTLIB)
+	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
+	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
+
+	echo "clang" >> $@
+	$(eval $@_DIR = $(patsubst %.al, $(BUILD_DIR)/test/perf/clang/%, $<))
+	clang $(CFLAGS) -c -O2 $(patsubst %.al, %.c, $<) -o $($@_DIR).o
+	clang $(LDFLAGS) -o $($@_DIR) $($@_DIR).o $(OBJS_ARCH) $(OBJS_STDLIB)
+	time -p $($@_DIR) 2> $($@_DIR).time || (echo "Test failed"; exit 1)
+	cat $($@_DIR).time | grep real | awk '{print $$2}' >> $@
+
 make_dir:
 	mkdir -p $(BUILD_DIR)/test/perf/x86_64
-	mkdir -p $(BUILD_DIR)/test/perf/c
+	mkdir -p $(BUILD_DIR)/test/perf/c-gcc
 	mkdir -p $(BUILD_DIR)/test/perf/gcc
+	mkdir -p $(BUILD_DIR)/test/perf/c-clang
+	mkdir -p $(BUILD_DIR)/test/perf/clang
